### ISSUE TITLE
Undefined function or variable 'mink'.

### ISSUE THREAD

**Issue by Annineli** [legendongary/BM3D-Net#1]
Undefined function or variable 'mink'.

Error in fast_nl_patches (line 100)
[vas, ods]=mink(SqDistFull, K);

Error in bm3d_net_res (line 8)
index = fast_nl_patches(resss, 3, 12, 8, mmind);

Error in demo (line 15)
resim = bm3d_net_res(noisy, sigma);

**Comment by legendongary** [comment]
[`mink`](https://www.mathworks.com/help/matlab/ref/mink.html) was introduced in Matlab R2017b. An alternative is to use the [`Min-Max Selection`](https://www.mathworks.com/matlabcentral/fileexchange/23576-min-max-selection) package, but it may crash when compiled using a newer compiler.
